=== lexnotor/pdf_plubishing/src/app/i18n/locales/contact.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "Tranlation of Contact Section",
    "properties": {
        "$schema": true,
        "title-1": {
            "$ref": "#/definitions/text"
        },
        "title-2": {
            "$ref": "#/definitions/text"
        },
        "title-3": {
            "$ref": "#/definitions/text"
        },
        "form-title": {
            "$ref": "#/definitions/text"
        },
        "form-p-1": {
            "type": "object",
            "properties": {
                "text-1": {
                    "$ref": "#/definitions/text"
                },
                "link-1": {
                    "$ref": "#/definitions/text"
                }
            },
            "required": ["text-1", "link-1"]
        },
        "form-p-2": {
            "type": "object",
            "properties": {
                "text-1": {
                    "$ref": "#/definitions/text"
                },
                "link-1": {
                    "$ref": "#/definitions/text"
                }
            }
        },
        "fname-placeholder": {
            "$ref": "#/definitions/text"
        },
        "lname-placeholder": {
            "$ref": "#/definitions/text"
        },
        "email-placeholder": {
            "$ref": "#/definitions/text"
        },
        "message-placeholder": {
            "$ref": "#/definitions/text"
        },
        "form-btn": {
            "$ref": "#/definitions/text"
        }
    },
    "required": [
        "title-1",
        "title-2",
        "title-3",
        "form-title",
        "form-p-1",
        "form-p-2",
        "form-btn",
        "fname-placeholder",
        "lname-placeholder",
        "email-placeholder"
    ],
    "definitions": {
        "text": {
            "type": "string"
        }
    },
    "additionalProperties": false
}

=== lexnotor/pdf_plubishing/src/app/i18n/locales/en/contact.json
{
    "$schema": "../contact.schema.json",
    "title-1": "Mailing Address",
    "title-2": "Phone Number",
    "title-3": "Press Contact",
    "form-title": "Send us a message",
    "form-p-1": {
        "text-1": "Please fill out the form below or you can send a direct email to info@gorillafund.org. Be sure to check out our Frequently Asked Questions page first,",
        "link-1": " by clicking here."
    },
    "form-p-2": {
        "text-1": "If you are contacting us for information regarding a questionable charge on your account please",
        "link-1": " visit here."
    },
    "fname-placeholder": "Firstname",
    "lname-placeholder": "Lastname",
    "email-placeholder": "Email Address",
    "message-placeholder": "Your comment or message",
    "form-btn": "Send message"
}

=== lexnotor/pdf_plubishing/src/app/i18n/locales/fr/contact.json
{
    "$schema": "../contact.schema.json",
    "title-1": "Adresse Postale",
    "title-2": "Téléphone",
    "title-3": "Contacts Presse",
    "form-title": "Envoyez nous un message",
    "form-p-1": {
        "text-1": "Veuillez remplir le formulaire ci-dessous ou envoyez un courriel direct à info@gorillafund.org. N'oubliez pas de consulter d'abord notre page Foire aux questions en",
        "link-1": " cliquant ici."
    },
    "form-p-2": {
        "text-1": "Si vous nous contactez pour obtenir des informations concernant un prélèvement douteux sur votre compte, veuillez",
        "link-1": " visiter ici."
    },
    "fname-placeholder": "Prenom",
    "lname-placeholder": "Post-nom",
    "email-placeholder": "Addresse Email",
    "message-placeholder": "Votre message",
    "form-btn": "Envoyer"
}
