=== lexnotor/pdf_plubishing/src/app/i18n/locales/footer.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "Tranlation of Footer Section",
    "properties": {
        "$schema": true,
        "article-1": {
            "$ref": "#/definitions/text"
        },
        "article-2": {
            "type": "object",
            "properties": {
                "head": { "$ref": "#/definitions/text" },
                "link-1": { "$ref": "#/definitions/text" },
                "link-2": { "$ref": "#/definitions/text" },
                "link-3": { "$ref": "#/definitions/text" }
            },
            "required": ["head", "link-1", "link-2", "link-3"]
        },
        "article-3": {
            "type": "object",
            "properties": {
                "head": { "$ref": "#/definitions/text" },
                "link-1": { "$ref": "#/definitions/text" },
                "link-2": { "$ref": "#/definitions/text" },
                "link-3": { "$ref": "#/definitions/text" }
            },
            "required": ["head", "link-1", "link-2", "link-3"]
        },
        "article-4": {
            "type": "object",
            "properties": {
                "head": { "$ref": "#/definitions/text" },
                "link-1": { "$ref": "#/definitions/text" },
                "link-2": { "$ref": "#/definitions/text" },
                "link-3": { "$ref": "#/definitions/text" }
            },
            "required": ["head", "link-1", "link-2", "link-3"]
        },
        "terms": {
            "$ref": "#/definitions/text"
        },
        "policy": {
            "$ref": "#/definitions/text"
        },
        "donor-policy": {
            "$ref": "#/definitions/text"
        },
        "copyright": {
            "$ref": "#/definitions/text"
        }
    },
    "required": [
        "article-1",
        "article-2",
        "article-3",
        "article-4",
        "terms",
        "policy",
        "donor-policy",
        "copyright"
    ],
    "definitions": {
        "text": {
            "type": "string"
        }
    },
    "additionalProperties": false
}

=== lexnotor/pdf_plubishing/src/app/i18n/locales/fr/footer.json
{
    "$schema": "../footer.schema.json",
    "article-1": "Nous contacter",
    "article-2": {
        "head": "Nous connaître",
        "link-1": "Qui sommes-nous",
        "link-2": "Que faisons nous",
        "link-3": "Nouvelles"
    },
    "article-3": {
        "head": "Contact",
        "link-1": "FAQ",
        "link-2": "Salle de presse",
        "link-3": "Visitez le campus Ellen"
    },
    "article-4": {
        "head": "Comment donner",
        "link-1": "Donnation",
        "link-2": "Adoption de gorille",
        "link-3": "Boutique"
    },
    "copyright": "© 2023 Dian Fossey Gorilla Fund Inc. Tout droit reservé.",
    "donor-policy": "POLITIQUE DE DONATIONS",
    "policy": "CONFIDENTIALITÉ",
    "terms": "CONDITIONS D'UTILISATION"
}

=== lexnotor/pdf_plubishing/src/app/i18n/locales/en/footer.json
{
    "$schema": "../footer.schema.json",
    "article-1": "Connect with us",
    "article-2": {
        "head": "Get to know us",
        "link-1": "Who we are",
        "link-2": "What we do",
        "link-3": "News"
    },
    "article-3": {
        "head": "Connect",
        "link-1": "FAQ",
        "link-2": "Pressroom",
        "link-3": "Visit the Ellen Campus"
    },
    "article-4": {
        "head": "Ways to give",
        "link-1": "Donate",
        "link-2": "Adopt a gorilla",
        "link-3": "Shop"
    },
    "copyright": "Â© 2023 Dian Fossey Gorilla Fund Inc. All right reserved",
    "donor-policy": "DONOR POLICY",
    "policy": "PRIVACY",
    "terms": "TERMS & CONDITIONS"
}
