=== lexnotor/pdf_plubishing/src/app/i18n/locales/header.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "Tranlation of Header Section",
    "properties": {
        "$schema": true,
        "p-1": {
            "type": "object",
            "properties": {
                "text-1": { "$ref": "#/definitions/text" },
                "text-2": { "$ref": "#/definitions/text" }
            },
            "required": ["text-1", "text-2"]
        },
        "p-2": {
            "type": "object",
            "properties": {
                "text-1": { "$ref": "#/definitions/text" },
                "text-2": { "$ref": "#/definitions/text" }
            },
            "required": ["text-1", "text-2"]
        },
        "btn-1": {
            "$ref": "#/definitions/text"
        },
        "btn-2": {
            "$ref": "#/definitions/text"
        },
        "navbar": {
            "type": "object",
            "properties": {
                "home": { "$ref": "#/definitions/text" },
                "programs": { "$ref": "#/definitions/text" },
                "about": { "$ref": "#/definitions/text" },
                "contact": { "$ref": "#/definitions/text" }
            },
            "required": ["home", "programs", "about", "contact"]
        },
        "search": {
            "type": "object",
            "properties": {
                "placeholder": { "$ref": "#/definitions/text" }
            },
            "required": ["placeholder"]
        }
    },
    "definitions": {
        "text": {
            "type": "string"
        }
    },
    "required": ["p-1", "p-2", "btn-1", "btn-2", "navbar", "search"],
    "additionalProperties": false
}

=== lexnotor/pdf_plubishing/src/app/i18n/locales/en/header.json
{
    "$schema": "../header.schema.json",
    "btn-1": "Our latest programs",
    "btn-2": "Follow Our Journey",
    "p-1": {
        "text-1": "Uncover enchanting stories and connect",
        "text-2": "with the beauty of the natural world"
    },
    "p-2": {
        "text-1": "Gorillas are beautiful, resilient animals. But poaching and habitat destruction ",
        "text-2": "have pushed their populations to the brink of extinction in recent decades"
    },
    "navbar": {
        "about": "About Us",
        "contact": "Contacts",
        "home": "Home",
        "programs": "Our Programs"
    },
    "search": {
        "placeholder": "Search ..."
    }
}

=== lexnotor/pdf_plubishing/src/app/i18n/locales/fr/header.json
{
    "$schema": "../header.schema.json",
    "btn-1": "Programmes recents",
    "btn-2": "Suivez notre voyage",
    "p-1": {
        "text-1": "Découvrir des histoires fascinantes et se connecter",
        "text-2": "à la beauté du monde naturel"
    },
    "p-2": {
        "text-1": "Les gorilles sont des animaux magnifiques et résistants. Mais le braconnage et la destruction de leur habitat ont",
        "text-2": "poussé leurs populations au bord de l'extinction au cours des dernières décennies"
    },
    "navbar": {
        "about": "A propos",
        "contact": "Contacts",
        "home": "Accueil",
        "programs": "Nos Programmes"
    },
    "search": {
        "placeholder": "Recherche ..."
    }
}
